[build]
builder = "NIXPACKS"

[build.nixpacks]
[build.nixpacks.phases.setup]
commands = [
  "cd backend && npm install",
  "cd frontend && npm install"
]

[build.nixpacks.phases.build]
commands = [
  "cd frontend && npm run build",
  "cd backend && npx prisma generate && npx prisma migrate deploy"
]

[build.nixpacks.phases.start]
commands = [
  "cd backend && npm start"
]
