# nixpacks.toml

# Fase de setup: instala dependências de backend e frontend
[phases.setup]
commands = [
  "cd backend && npm install",
  "cd frontend && npm install"
]

# Fase de build: gera o Prisma Client
[phases.build]
commands = [
  "cd backend && npx prisma generate"
  # Se tiver build do frontend, ex: "cd frontend && npm run build"
]

# Fase de start: inicia somente o backend, que também serve o frontend
[phases.start]
commands = [
  "cd backend && npm start"
]
