builder = "NIXPACKS"

[phases.setup]
commands = [
  "npm --prefix backend install",
  "npm --prefix frontend install"
]

[phases.build]
commands = [
  "npm --prefix frontend run build",
  "npx --prefix backend prisma generate",
  "npx --prefix backend prisma migrate deploy"
]

[phases.start]
commands = [
  "npm --prefix backend start"
]
