# Instala dependências de backend e frontend
[phases.setup]
commands = [
  "cd backend && npm install",
  "cd frontend && npm install"
]

# Gera o Prisma Client
[phases.build]
commands = [
  "cd backend && npx prisma generate"
]

# Inicia o backend (que também serve o frontend)
[phases.start]
commands = [
  "cd backend && npm start"
]
