[build]
builder = "NIXPACKS"

[build.nixpacks]
phases.setup.commands = [
  "cd backend && npm install",
  "cd frontend && npm install"
]
phases.build.commands = [
  "cd frontend && npm run build",
  "cd backend && npx prisma generate && npx prisma migrate deploy"
]
phases.start.commands = [
  "cd backend && npm start"
]
