# nixpacks.toml

# Fase de setup: instala dependências de backend e frontend
[phases.setup]
commands = [
  # Backend
  "cd backend && npm install",
  # Frontend (serve)
  "cd frontend && npm install"
]

# Fase de build: gera o Prisma Client
[phases.build]
commands = [
  "cd backend && npx prisma generate"
  # Se você tiver um passo de build no frontend (ex: Vite), adicione aqui
]

# Fase de start: inicia somente o backend, que também serve o frontend
[phases.start]
command = "cd backend && npm start"
