# Instala dependências de backend e frontend
[phases.setup]
commands = [
  "cd backend && npm install",
  "cd frontend && npm install"
]

# Gera o Prisma Client e aplica migrations em produção
[phases.build]
commands = [
  "cd backend && npx prisma generate && npx prisma migrate deploy"
]

# Inicia o backend (que já serve o diretório frontend/public)
[phases.start]
commands = [
  "cd backend && npm start"
]
